/*
 * photo viewer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetPhotos - 
func GetPhotos(c *gin.Context) {
	var photos []PhotoProperties
	res := Photos{
		Photos: photos,
	}
	c.JSON(http.StatusOK, res)
}
