/*
 * photo viewer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PhotoProperties struct {

	Id int32 `json:"id"`

	Title string `json:"title,omitempty"`

	Path string `json:"path,omitempty"`
}
